- name: システムを再起動する
  become: yes
  become_method: su
  shell: /sbin/shutdown -r
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for sshd to shutdown
  become: no 
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    state: stopped
    port: 45345

- name: waiting for server to come back
  become: no 
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    state: started

###    port: 22
###    delay: 30 
###    timeout: 300
### ディレイやタイムアウトを設定してもさくらVPSだとうまく行かない
### 時間が4分ほど余分に掛かるが state=started を利用した方が確実

#- name: enter pass
#  expect:
#    command:
#    response:
#      "*": "yuchan55"

#- name: resister system started date time for debug
#  expect:
#    command: /bin/bash -l "ps -p 1 -o lstart"
#    responses:
#      "^Enter passphrase*": "yuchan55"
#  register: RESULT

#- name: show system started date
#  debug: var=RESULT.stdout_lines
  
