- name: 開発ツールをインストールする
  become: yes
  yum:
    name: '@Development Tools'
    state: present 

- name: EPELをインストールする
  become: yes
  include_role:
    name: system/packages/epel/install

- name: 必要なパッケージをインストールする
  become: yes
  yum:
    name: '{{ item }}'
    state: present 
  loop:
    - expect
    - openssl-devel
    - python-devel

- name: pipをインストールする
  become: yes
  yum:
    name: 'python-pip'
    state: present

- name: pipをアップグレードする
  become: yes
  pip:
    name: pip
    extra_args: --upgrade

- name: setuptoolsをアップグレードする
  become: yes
  pip:
    name: setuptools
    extra_args: --upgrade

- name: Ansibleをインストールする 
  become: yes
  pip:
    name: git+git://github.com/ansible/ansible.git@devel
