- name: EPELをインストールする
  become: yes
  include_role:
    name: system/packages/epel/install

- name: 必要なパッケージをインストールする
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  loop:
    - expect
    - openssl-devel
    - python-devel

- name: pipをインストールする
  become: yes
  include_role:
    name: system/pip/install

- name: Ansibleをインストールする
  become: yes
  pip:
    name: git+git://github.com/ansible/ansible.git@devel
