- name: Remiリポジトリをインストールする
  become: yes
  include_role:
    name: system/packages/remi/install

- name: ImageMagickとヘッダファイルをインストールする
  become: yes
  yum:
    name: '{{ item }}'
    enablerepo: remi
    state: present 
  loop:
    - ImageMagick7
    - ImageMagick7-devel
    - ImageMagick7-libs
