# jenkins restore vars

# Ansibleクライアントが所有するJenkinsバックアップデータファイルのディレクトリ（フルパスで指定する）
local_data_dir: /tmp/jenkins-backup-data

# 作業用ディレクトリ
work_dir: /tmp/jenkins-restore

# jenkinsバックアップデータファイルのアーカイブスファイル
data_file: jenkins.tar.gz

# Jenkinsがインストールされているディレクトリ
jenkins_installed_dir: /var/lib/jenkins

# Jenkinsを実行するユーザー名
jenkins_excute_user: jenkins

# Jenkinsのシステム管理者名
jenkins_admin_user: admin
