- name: Jenkinsのディレクトリを設定する  
  lineinfile:
    dest: /etc/sysconfig/jenkins
    state: present
    regexp: 'JENKINS_ARGS=""'
    line: 'JENKINS_ARGS="--prefix=/{{ jenkins_dir }}"'

- name: "{{ httpd_conf_confd }}を作成する"
  become: yes
  template: 
    src: jenkins.conf
    dest: "/etc/httpd/conf.d/{{ httpd_conf_confd }}"
    owner: root
    group: root 
    mode: 0644

- name: アクセス制限を設けるIPアドレスまたはドメイン名を指定する 
  become: yes
  lineinfile:
    path: "/etc/httpd/conf.d/{{ httpd_conf_confd }}"
    insertbefore: '</Proxy>'
    line: "  {{ item.value }}"
  with_dict: '{{ requires }}'

- name: httpdを再起動する
  become: yes
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: Jenkinsを再起動する
  become: yes
  service:
    name: jenkins
    state: restarted 
    enabled: yes
