- name: 作業ディレクトリを初期化する
  become: yes
  file:
    path: '{{ work_dir }}'
    state: absent

- name: 作業ディレクトリ作成
  become: yes
  file: 
    path: '{{ work_dir }}'
    state: directory
    mode: 0755

- name: PostgreSQL initdb
  become: yes
  command:
    postgresql-setup initdb
  environment:
    PATH:
      "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }} "
  register:
    result
  failed_when:
    result.rc not in [0, 1]
  changed_when:
    result.rc == 0

- name: pg_hba.confにredmine用設定が存在するか確認
  become: yes
  command:
    "grep redmine {{ pg_hba_conf_path }}"
  register:
    result_pg_hba
  failed_when:
    result_pg_hba.rc not in [0, 1]
  changed_when: false

- name: pg_hba.conf設定変更用パッチを配置
  become: yes
  copy:
    src: pg_hba_conf.patch
    dest: '{{ work_dir }}'
  when: result_pg_hba.rc == 1

- name: pg_hba.confにredmine用設定を追加
  become: yes
  shell:
    patch -tNp0 {{ pg_hba_conf_path }} < {{ work_dir }}/pg_hba_conf.patch
  when: result_pg_hba.rc == 1

- name: PostgreSQL起動
  become: yes
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: postgresを一時的にsudoersに追加する
  become: yes
  environment:
    PATH:
      "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }} "
  lineinfile: 
    dest: /etc/sudoers.d/postgres
    owner: root
    group: root
    mode: 0440
    line: "%{{ ansible_user_id }} ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name: PostgreSQL ユーザー作成
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user:
    name: redmine
    password: '{{ db_password }}'

- name: PostgreSQL データベース作成
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db:
    name: redmine
    encoding: UTF-8
    lc_collate: ja_JP.UTF-8
    lc_ctype: ja_JP.UTF-8
    template: template0

- name: postgresをsudoersから削除する
  become: yes
  file:  
    path: /etc/sudoers.d/postgres
    state: absent
