- name: SSH接続ポートを削除する
  become: yes
  firewalld:
    port: "{{ ssh_port }}/tcp"
    permanent: true
    state: disabled

- name: 「/etc/firewalld/services/ssh.xml」を削除する
  become: yes
  file:
    path: /etc/firewalld/services/ssh.xml
    state: absent

- name: 変更されているsshd_configを削除する
  become: yes
  file:
    path: /etc/ssh/sshd_config
    state: absent

- name: 初期状態のsshd_configを作成する
  become: yes
  copy: 
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0600

- name: Firewallの設定を反映させる
  become: yes
  shell: firewall-cmd --reload

- name: sshdを再起動する
  become: yes
  service:
    name: sshd
    state: restarted

- name: sshdが停止するまで待機する
  become: no
  local_action: wait_for
  args:
    host: '{{ inventory_hostname }}'
    port: '{{ ssh_port }}'
    state: stopped

- name: sshdが起動するまで待機する 
  become: no
  local_action: wait_for
  args:
     host: '{{ inventory_hostname }}'
     port: 22
     state: started
     delay: 15

#- name: ログアウトする
#  become: yes
#  shell:
#    "ps ax | grep sshd | grep {{ ansible_user_id }} | kill `awk {'print $1'}`" 
