- name: バックアップデータ格納ディレクトリを初期化する / 初期化処理
  become: yes
  file:
    path: '{{ backup_data_path }}'
    state: absent

- name: バックアップデータ格納ディレクトリを作成する
  become: yes
  file:
    path: '{{ backup_data_path }}'
    state: directory
    mode: 0755

- name: PostgreSQLダンプデータを削除する / 初期化処理
  become: yes
  file:
    path: "/tmp/{{ redmine_media_archive_file }}"
    state: absent

- name: Gitリポジトリをアーカイブする
  become: yes
  archive:
    path: '{{ git_dir }}'
    dest: '{{ backup_data_path }}/git.tar.gz'
    owner: '{{ backup_data_owner }}'
    group: '{{ backup_data_group }}'
    mode: 0755

- name: メディアファイルをアーカイブする
  become: yes
  archive:
    path: "{{ redmine_dir }}/files"
    dest: '{{ backup_data_path }}/files.tar.gz'
    owner: '{{ backup_data_owner }}'
    group: '{{ backup_data_group }}'
    mode: 0755

- name: PostgreSQL / データベース「redmine」をダンプする
  become: yes
  environment:
    PGPASSWORD: '{{ db_password }}'
  shell:
    "pg_dump -h localhost -U {{ db_user }} {{ db_name }} > /tmp/{{ pg_dump_data_file }}"

- name: PostgreSQLダンプファイルを公開ディレクトリへ移動する
  become: yes
  copy:
    src:
      "/tmp/{{ pg_dump_data_file }}"
    dest:
      "{{ backup_data_path }}/{{ pg_dump_data_file }}"
    owner: '{{ backup_data_owner }}'
    group: '{{ backup_data_group }}'
    mode: 0755
    remote_src: yes

- name: PostgreSQLダンプデータを削除する
  become: yes
  file:
    path: "/tmp/{{ pg_dump_data_file }}"
    state: absent
