- name: Zabbix Yum リポジトリを登録する
  become: yes 
  yum:
    name: '{{ zabbix_release_rpm_url }}'
    state: present 

- name: Zabbix をインストールする 
  become: yes
  yum:
    name: '{{ item }}'
    enablerepo: remi-php71
    state: present 
  with_items:
    - zabbix-server-mysql 


- name: httpdを再起動する
  become: yes
  service:
    name: httpd
    state: restarted
    enabled: yes
