- name: 作業用ディレクトリを初期化する
  become: yes
  file:
    path: '{{ restore_work_dir }}'
    state: absent

- name: 作業用ディレクトリを作成する
  become: yes
  file:
    path: '{{ restore_work_dir }}'
    state: directory
    mode: 0755

- name: GitHubから作業用ディレクトリへ WordPress バックアップデータを取得する
  become: yes
  git:
    repo: '{{ wp_git_repo }}'
    dest: '{{ restore_work_dir }}'
    version: '{{ wp_git_repo_version }}'
