---
- hosts: all
  vars_files:
    - vars/jenkins/install/default.yml
  become: yes

  roles:
    - role: jenkins/uninstall
      tags: jenkins_uninstall
    - role: system/firewall/jenkins/remove-ports/
      tags: system_firewall_jenkins_remove-ports/
    - role: jenkins/reset-proxy-and-access-restriction
      tags: jenkins_reset-proxy-and-access-restriction
