---
- hosts: all
  vars_files:
    - vars/wordpress/restore/github/default.yml
  become: yes

  roles:
    - wordpress/get-backup-data/github
    - wordpress/restore-wp-content
    - wordpress/restore-database
