- name: 作業用ディレクトリを初期化する
  become: yes
  file:
    path: '{{ restore_work_dir }}'
    state: absent 

- name: 作業用ディレクトリを作成する
  become: yes
  file:
    path: '{{ restore_work_dir }}'
    state: directory
    mode: 0755

- name: 作業用ディレクトリへ Redmine PostgreSQL バックアップファイルをダウンロードする
  become: yes
  get_url:
    url: '{{ psql_backup_url }}'
    dest: '{{ restore_work_dir }}'
    mode: 0755

- name: Gitリポジトリ管理用アカウント（git）を作成する
  become: yes
  user:
    name: git

- name: リモートサーバからGitリポジトリを取得する
  become: yes
  unarchive:
    src: '{{ git_backup_url }}'
    dest: /var
    owner: git
    group: git
    mode: 0755
    remote_src: yes

- name: リモートサーバからRedmineメディアファイルを取得する
  become: yes
  unarchive:
    src: '{{ file_backup_url }}'
    dest: /var/lib/redmine
    owner: apache
    group: apache
    mode: 0755
    remote_src: yes
