- name: Gitリポジトリのリストを取得する
  become: yes
  shell:
    "find /var/git -name HEAD -execdir test -e refs -a -e objects -a -e config \\; -printf %h\\\\n | sort"
  register: GIT_REPOS

- name: Gitリポジトリの設定を取得する
  become: yes
  shell: "git config --list | grep 'receive.denydeletecurrent'"
  args:
    chdir: '{{ item }}'
  with_items:
    - "{{ GIT_REPOS.stdout_lines }}"
  register: GIT_CONFIGS
  failed_when: "'receive.denydeletecurrent' in GIT_CONFIGS.stdout"
