- name: EPELをインストールする
  become: yes
  include_role:
    name: system/packages/epel/install

- name: TigerVNC Serverをインストールする
  become: yes
  yum:
    name: 'tigervnc-server'
    state: present

- name: VNCサーバの設定 / 設定ファイルをコピーする
  become: yes
  copy:
    src: /lib/systemd/system/vncserver@.service
    dest: /etc/systemd/system/vncserver@:1.service
    remote_src: yes

- name: VNCサーバの設定 / 設定ファイルを変更する
  become: yes
  replace: 
    dest: /etc/systemd/system/vncserver@:1.service
    regexp: '<USER>'
    replace: "{{ vnc_user }}"

- name: VNCユーザーを追加する
  become: yes
  user: 
    name: "{{ vnc_user }}"
    password: "{{ vnc_password }} | password_hash('sha512')"

- name: 「$HOME/.vnc」を作成する
  file:
    path: "/home/{{ vnc_user }}/.vnc"
    state: directory
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0755

- name: 「$HOME/.vnc/passwd」を作成する
  shell: "echo {{ vnc_password }} | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd"

- name: 「$HOME/.vnc/passwd」の権限を変更する
  file:
    path: "/home/{{ vnc_user }}/.vnc/passwd"
    state: file
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0600

- name: TigerVNC Server を起動する
  become: yes
  systemd:
    name: vncserver@:1.service
    state: started
    enabled: yes
    daemon_reload: yes
