- name: 「my.cnf」を「/root/.my.cnf」へコピーする
  become: yes
  template:
    src: my.cnf
    dest: /root/.my.cnf
    mode: 0600

- name: データベースを削除する
  become: yes
  mysql_db:
    name: '{{ db_name }}' 
    state: absent 

- name: 「/root/.my.cnf」を削除する
  file:
    path: /root/.my.cnf
    state: absent
