# Redmine restore vars

# Redmine backup data host
#
# 変数は適宜変更する
#
# または「--extra-vars "param1=value1 param2=value2"」と
# ansible-playbookコマンド実行時にパラメーターとして渡す
#---------------------------------------------
backup_data_host: http://example.com
# Db user
db_user: redmine
# Db password
db_password: password
# Db name:
db_name: redmine
#---------------------------------------------

redmine_dir: /var/lib/redmine

# Redmine backup data dir
backup_data_dir: redmine-backup

# Restore working directory
restore_work_dir: /tmp/redmine-restore

# Redmine database dump data file name
pg_dump_file: redmine.psql

# Redmine media files archive file name
redmine_files_archive_file: files.tar.gz

# Git repository archive file name
git_archive_file: git.tar.gz

