- name: システム全体をアップデートする
  sudo: yes
  yum: name=* state=latest

- name: SELinuxの状態確認
  command:
    /usr/sbin/selinuxenabled
  register:
    result
  changed_when: false
  failed_when: result.rc not in [0, 1]

- name: 起動時にSELinux無効化 (/etc/sysconfig/selinux)
  selinux: state=disabled
  when: result.rc == 0

- name: EPELをインストール
  yum:
    name: 'epel-release'
    state: present

- name: 日本語関連のパッケージをインストール
  yum:
    name: ibus-kkc
    state: present

- name: 日本語関連のパッケージをインストール
  yum:
    name: vlgothic-*
    state: present

- name: システムの文字セットをUTF-8へ変更
  shell: localectl set-locale LANG=ja_JP.UTF-8

- name: システムの文字セットの変更を繁栄させる
  shell: source /etc/locale.conf

- name: pipをインストール
  yum:
    name: python-pip
    state: present

- name: pipをアップデート
  shell: pip install --upgrade pip

- name: pexpectをインストール #Ansibleでexpectを利用するためのライブラリ
  shell: pip install pexpect

- name: VNCサーバ構築に必要なツールのインストール
  yum:
    name: 'tigervnc-server'
    state: present

- name: GNOMEデスクトップをインストール
  shell: yum -y groupinstall GNOME Desktop

- name: VNCサーバの設定 / 設定ファイルのコピー
  shell: cp /lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@:1.service

- name: VNCサーバの設定 / 設定ファイルの書き換え
  replace: 
    dest: /etc/systemd/system/vncserver@:1.service
    regexp: '<USER>'
    replace: "{{ vnc_user }}"

- name: ファイアウォールの設定 / vnc-serverを追加
  shell: firewall-cmd --permanent --add-service vnc-server

- name: ファイウォールの設定 / ファイアウォールを再スタート
  shell: systemctl restart firewalld.service

- name: VNCユーザーの設定 / VNCユーザーを追加
  user: 
    name: "{{ vnc_user }}"

- name: VNCユーザーの設定 / VNCパスワードを設定
  become: yes
  become_user: "{{ vnc_user }}"
  expect:
    command: vncpasswd 
    responses:
      "Password:" : "{{ vnc_password }}"
      "Verify:" : "{{ vnc_password }}"

- name: systemdに設定ファイルを再度読込みをさせる
  shell: systemctl daemon-reload

# - name: VNCサービスの停止 (http://srobb.net/rhvnc.html)
#   shell: pkill vnc

- name: VNCサービスの起動
  shell: systemctl start vncserver@:1.service

- name: VNCサービスの自動起動設定を行う
  shell: systemctl enable vncserver@:1.service
