# wp-cliがインストールされているか調べる時に利用
wp_install_work_dir: /tmp/wp-install

# Wordpress create backup data vars

#----------------------------------------
# 適宜変更する
#----------------------------------------
# Db dump file name
db_dump_data_sql: wordpress.sql
#----------------------------------------

# Backup data dir
backup_data_dir: wordpress-backup

# Backup data group
backup_data_group: root

# Backup data owner
backup_data_owner: root

# Backup data path
backup_data_path: "/var/www/html/{{ backup_data_dir }}"

# WordPress installed path
wp_installed_path: /var/www/html/wordpress

wp_url: http://example.com

replace_url: http://exmample2.com
