- name: Remiリポジトリをインストールする 
  become: yes
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present 

- name: Remi GPGキーを追加する
  become: yes
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
