- name: 「vnc/server/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/vnc/server/install'
    recurse: yes
    state: directory

- name: 「vnc/server/install」をbinディレクトリに配置する
  template:
    src: install
    dest: '{{ ansible_user_dir }}/ansible/bin/vnc/server/install/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"
