- name: Apache（httpd）をアンインストールする
  become: yes
  yum: 
    name: httpd 
    state: absent

- name: firewalldでHTTPポートを無効にする
  become: yes
  firewalld: 
    service: http
    state: disabled
    permanent: true
    immediate: true
