# ownCloudデータベース情報                                                                  
# 環境に応じて変更する事                                                                     
#----------------------------------------------------                                        
db_name: owncloud 
db_user: owncloud
db_password: owncloud 
db_host: localhost                                                                           
oc_install_dir: /var/www/html/owncloud

#----------------------------------------------------                                        
# Apacheの.htaccessを制御するファイル
httpd_conf_confd: owncloud.conf
#----------------------------------------------------

#----------------------------------------------------                                        
# アクセスをコントロールするIPアドレス／ドメイン
#----------------------------------------------------                                        
requires:
  example.com: Require host example.com
  127.0.0.1: Require ip 127.0.0.1
  
