- name: 「my.cnf」を「/root/.my.cnf」へコピーする
  become: yes
  template:
    src: my.cnf
    dest: /root/.my.cnf
    mode: 0600

- name: データベースを作成する
  become: yes
  mysql_db:
    name: '{{ db_name }}' 
    state: present

- name: データベース {{ db_name }} に対しユーザー {{ db_user }} の権限を与える
  become: yes
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    state: present
    priv: "{{ db_user }}.*:ALL"
    host: localhost

- name: 「/root/.my.cnf」を削除する
  file:
    path: /root/.my.cnf
    state: absent
