- name: システムを再起動する
  become: yes
  shell: /sbin/shutdown -r
  async: 1
  poll: 0
  ignore_errors: yes 

- name: sshdが停止するまで待機する 
  become: no 
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    state: stopped
    port: '{{ ansible_port }}'

- name: システムが再起動するまで待機する 
  become: no 
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    state: started
    timeout: 60
