- name: kernel-headers-* を切り換える
  become: yes
  shell:
    yum --enablerepo=elrepo-kernel -y swap kernel-headers -- kernel-ml-headers

- name: kernel-tools-libs-* を切り換える
  become: yes
  shell:
    yum --enablerepo=elrepo-kernel -y swap kernel-tools-libs -- kernel-ml-tools-libs

- name: kernel-ml-tools をインストールする
  become: yes
  yum:
    name: kernel-ml-tools
    enablerepo: elrepo-kernel
    state: present

- name: kernel-devel-* を切り換える
  become: yes
  shell:
    yum --enablerepo=elrepo-kernel -y swap kernel-devel -- kernel-ml-devel

- name: 古いカーネルを削除する
  become: yes
  yum:
    name: kernel
    state: absent
  ignore_errors: yes
