- name: EPELをインストールする
  become: yes
  include_role:
    name: system/packages/epel/install

- name: pipをインストールする
  become: yes
  include_role:
    name: system/pip/install

- name: AWS CLIをインストールする
  become: yes
  pip:
    name: awscli
