# WordPressインストール情報
# 環境に応じて変更する事
#----------------------------------------------------
wp_install_dir: wordpress
wp_install_path: "/var/www/html/{{ wp_install_dir }}"
#----------------------------------------------------

# WordPressデータベース情報
# 環境に応じて変更する事
#----------------------------------------------------
db_name: wordpress
db_user: wordpress
db_password: wordpress
db_host: localhost
db_port: 3306
#----------------------------------------------------

# Apacheの.htaccessを制御するファイル
wp_httpd_conf: wordpress.conf
#----------------------------------------------------
