- name: 作業用ディレクトリを初期化する
  become: yes
  file:
    path: '{{ work_dir }}'
    state: absent

- name: 作業用ディレクトリを作成する
  become: yes
  file:
    path: '{{ work_dir }}'
    state: directory
    mode: 0755

- name: 作業用ディレクトリへ Jenkins バックアップファイルをダウンロードする (Ansible クライアントからアップロードする）
  become: yes
  unarchive:
    src: '{{ local_data_dir }}/{{ data_file }}'
    dest: '{{ work_dir }}'

- name: Jenkinsを停止する
  become: yes
  service:
    name: jenkins
    state: stopped

- name: 稼働中のJenkinsのデータを削除する
  become: yes
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /var/cache/jenkins/*
    - "{{ jenkins_installed_dir }}/jobs/"
    - "{{ jenkins_installed_dir }}/nodes/"
    - "{{ jenkins_installed_dir }}/plugins/"
    - "{{ jenkins_installed_dir }}/users/"
    - "{{ jenkins_installed_dir }}/secrets/"

- name: Jenkinsバックアップデータを配置する
  become: yes
  shell: "mv -f * {{ jenkins_installed_dir }}"
  args:
    chdir: '{{ work_dir }}'

- name: Jenkinsのシステムファイルの所有権をrootからJenkinsへ変更する
  become: yes
  file:
    path: '{{ jenkins_installed_dir }}'
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Jenkinsを起動する
  become: yes
  service:
    name: jenkins
    state: started
    enabled: yes
