- name: WP-CLIをダウンロードする
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /tmp
    owner: root
    group: root
    mode: 0755

- name: WP-CLIをコマンドに登録する
  become: yes
  shell: mv wp-cli.phar /usr/local/bin/wp
  args:
    chdir: /tmp

- name: WordPressインストールディレクトリを作成する
  become: yes
  file:
    dest: '{{ wp_install_path }}'
    state: directory
    owner: apache
    group: apache
    mode: 0755
    recurse: yes

- name: WordPressをダウンロードし解凍する
  become: yes
  shell:
    "sudo -u apache /usr/local/bin/wp core download --path={{ wp_install_path }}" 

- name: 「wp-config.php」を作成する
  become: yes
  shell:
    "sudo -u apache /usr/local/bin/wp core config --dbname={{ db_name }} --dbuser={{ db_user }} --dbpass={{ db_password }} --dbhost={{ db_host }} --dbprefix={{ db_prefix }}"
  args:
    chdir: '{{ wp_install_path }}'

- name: WordPressをインストールする
  become: yes
  shell: 
    "sudo -u apache /usr/local/bin/wp core install  --url={{ wp_url }} --title={{ wp_title }} --admin_user={{ wp_admin_user }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }} --allow-root"
  args:
    chdir: '{{ wp_install_path }}'

- name: WordPress日本語ライブラリをインストールする
  become: yes
  shell: 
    "sudo -u apache /usr/local/bin/wp core language install ja"
  args:
    chdir: '{{ wp_install_path }}'
  
- name: WordPressを日本語化する
  become: yes
  shell: 
    "sudo -u apache /usr/local/bin/wp core language activate ja"
  args:
    chdir: '{{ wp_install_path }}'
