- name: システム全体をアップデートする
  become: yes
  yum:
    name: "*"
    state: latest
  register: SYSTEM_UPDATED 

- name: システムを再起動する
  become: yes
  include_role:
    name: system/reboot
  when: SYSTEM_UPDATED is changed
