- name: WP-CLIがインストールされているか調べる
  shell: sudo -u apache /usr/local/bin/wp --version --allow-root
  register: WPCLI_INSTALLED
  ignore_errors: yes 

- name: 作業用ディレクトリを初期化する
  become: yes
  file:
    path: '{{ wp_install_work_dir }}'
    state: absent
  when: WPCLI_INSTALLED is failed 

- name: 作業用ディレクトリを作成する 
  become: yes
  file:
    path: '{{ wp_install_work_dir }}'
    state: directory
    mode: 0755
  when: WPCLI_INSTALLED is failed 

- name: WP-CLIをダウンロードする
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: '{{ wp_install_work_dir }}'
    owner: root
    group: root
    mode: 0755
  when: WPCLI_INSTALLED is failed 

- name: WP-CLIをコマンドに登録する
  become: yes
  shell: mv wp-cli.phar /usr/local/bin/wp
  args:
    chdir: '{{ wp_install_work_dir }}'
  when: WPCLI_INSTALLED is failed 
