- name: owncloudリポジトリを追加する
  become: yes
  yum_repository:
    name: ce_stable 
    description: ownCloud Server Version stable (CentOS_7) 
    baseurl: http://download.owncloud.org/download/repositories/stable/CentOS_7
    file: ce:stable 
    gpgkey: https://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key 
    gpgcheck: yes
    enabled: yes

- name: owncloud-filesをインストールする
  become: yes
  yum:
    name: owncloud-files
    state: present
