- name: Javaをインストールする 
  become: yes
  yum: 
    name: java
    state: latest

- name: Jenkinsリポジトリをシステムに追加する
  become: yes
  yum_repository:
    name: jenkins
    description: Jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: yes
    gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

- name: Jenkinsをインストールする
  become: yes
  yum:
    name: jenkins
    state: latest

- name: Jenkinsを起動する
  become: yes
  service:
    name: jenkins
    state: started 
    enabled: yes

- name: JenkinsがAnsible Playbookを実行できるようにsudoersに登録する
  become: yes
  environment:
    PATH:
      "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }} " 
  lineinfile: 
    dest: /etc/sudoers.d/jenkins
    owner: root
    group: root
    mode: 0440
    line: "{{ item }}" 
    state: present
    create: yes
    validate: "visudo -cf %s" 
  with_items:
    - "jenkins ALL=({{ ansible_user_id }}) NOPASSWD: ALL" 
    - "Defaults:jenkins !requiretty" 
