- name: PostgreSQLを再起動する
  become: yes
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: ユーザー「postgres」を一時的にsudoersに追加する
  become: yes
  environment:
    PATH:
      "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }} "
  lineinfile: 
    dest: /etc/sudoers.d/postgres
    owner: root
    group: root
    mode: 0440
    line: "%ios ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name: PostgreSQL / データベース「redmine」を削除する
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db:
    name: redmine
    state: absent 

- name: PostgreSQL / データベース「redmine」を作成する
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db:
    name: redmine
    encoding: UTF-8
    lc_collate: ja_JP.UTF-8
    lc_ctype: ja_JP.UTF-8
    template: template0

- name: PostgreSQL / データベース「redmine」をリストアする
  become: yes
  become_user: postgres
  become_method: sudo
  environment:
    PGPASSWORD: '{{ db_passwd_redmine }}'
  shell:
    "psql -h localhost -U redmine redmine < {{ redmine_restore_work_dir }}/redmine.psql"

- name: データベースのマイグレーションを実行する
  become: yes
  command: bundle exec rake db:migrate
  args:
    chdir: '{{ redmine_dir }}'
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: キャッシュとセッションデータをクリアする
  become: yes
  command: bundle exec rake tmp:cache:clear tmp:sessions:clear 
  args:
    chdir: '{{ redmine_dir }}'
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: Apacheを再起動する
  become: yes
  service:
    name: httpd 
    state: restarted
    enabled: yes

- name: postgresをsudoersから削除する
  become: yes
  file:  
    path: /etc/sudoers.d/postgres
    state: absent
