# Zabbixデータベース情報
# 環境に応じて変更する事
#----------------------------------------------------
db_name: zabbix 
db_user: zabbix
db_password: zabbix
db_host: localhost
db_port: 3306
#----------------------------------------------------


# Zabbix RPM URL
zabbix_release_rpm_url: http://repo.zabbix.com/zabbix/3.5/rhel/7/x86_64/zabbix-release-3.5-1.el7.noarch.rpm 
