- name: Rubyがシステムにインストールされているか確認する
  shell: ruby -v
  register: result
  ignore_errors: true 

- name: Rubyインストールに必要なパッケージをインストールする
  become: yes
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - bzip2
    - curl-devel
    - gcc
    - gdbm-devel
    - git
    - libffi-devel
    - libyaml-devel
    - ncurses-devel
    - openssl-devel
    - readline-devel
    - zlib-devel
  when: result|failed

- name: 古い rbenv リポジトリを削除する
  become: yes
  file: 
    path: /root/.rbenv
    state: absent
  when: result|failed

- name: rbenv ruby-build を git clone する
  become: yes
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
  with_items:
    - repo: https://github.com/rbenv/rbenv.git
      dest: /root/.rbenv
    - repo: https://github.com/rbenv/ruby-build.git
      dest: /root/.rbenv/plugins/ruby-build
  when: result|failed
 
- name: bashにrbenvのパスを反映させる
  become: yes
  lineinfile:
    dest: /root/.bash_profile
    line: '{{ item }}'
    state: present
  with_items:
    - 'export PATH="$HOME/.rbenv/bin:$PATH"'
    - 'eval "$(rbenv init -)"'
  when: result|failed

- name: .bash_profileをリロードする
  become: yes
  shell: bash -lc "source /root/.bash_profile"
  when: result|failed

- name: Ruby 2.3.3 をインストールする
  become: yes
  shell: bash -lc "rbenv install -v 2.3.3"
  when: result|failed

- name: rbenvをリロードする
  become: yes
  shell: /bin/bash -lc "rbenv rehash"
  when: result|failed

- name: Ruby 2.3.3 をシステムで利用するRubyのバージョンに設定する
  become: yes
  shell: /bin/bash -lc "rbenv global 2.3.3"
  when: result|failed

- name: Rubyのバージョンを確認する
  shell: ruby -v
  register: RUBY_VERSION_VARS_FINAL 

- name: Rubyが無事インストール出来たか確認する
  debug: var=RUBY_VERSION_VARS_FINAL
