- name: 「my.cnf」を「/root/.my.cnf」へコピーする
  become: yes
  template:
    src: my.cnf
    dest: /root/.my.cnf
    mode: 0600

- name: データベースを作成する
  become: yes
  mysql_db:
    name: '{{ mariadb_name }}' 
    state: present

- name: データーベース {{ mariadb_name }} に対しユーザー {{ mariadb_user }} の権限を与える
  become: yes
  mysql_user:
    name: '{{ mariadb_user }}'
    password: '{{ mariadb_password }}'
    state: present
    priv: "{{ mariadb_user }}.*:ALL"
    host: localhost

- name: 「/root/.my.cnf」を削除する
  file:
    path: /root/.my.cnf
    state: absent
