# Wordpress restore vars

# 作業用ディレクトリ 
restore_work_dir: /tmp/wordpress-backup

#----------------------------------------
# 適宜変更する
#----------------------------------------
# WordPress バックアップ SQL データが置かれているURL
sql_backup_url: http://example.com/wp.sql

# WordPress バックアップ SQL データファイル名
sql_dump_file: wordpress.sql

# WordPress wp-content ディレクトリのバックアップデータが置かれているURL
wp_content_backup_url: http://example.com/wp-content.tar

# WordPress がインストールされているパス
wp_installed_path: /var/www/html/wordpress

# リストアされる WordPress の URL
wp_new_url: http://example.com/wp-new

# バックアップデータを作成した WordPress の URL
wp_old_url: http://example.com/wp-old
#----------------------------------------
