- name: 各サーバのPlaybookトリーガースクリプトを配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}'
    state: directory
  with_dict: "{{ ipv4 }}"

- name: 「jenkins_install」をbinディレクトリに配置する
  template:
    src: jenkins_install
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「owncloud_install」をbinディレクトリに配置する
  template:
    src: owncloud_install
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「redmine_install」をbinディレクトリに配置する
  template:
    src: redmine_install
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「redmine_restore」をbinディレクトリに配置する
  template:
    src: redmine_restore
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「selenium_python_install」をbinディレクトリに配置する 
  template:
    src: selenium_python_install
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「system_language_ruby_install_rbenv_2.3.3」をbinディレクトリに配置する
  template:
    src: system_language_ruby_install_rbenv_2.3.3 
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「system_ssh_add-users-and-change-sshd-config-and-firewall」をbinディレクトリに配置する 
  template:
    src: system_ssh_add-users-and-change-sshd-config-and-firewall 
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"


- name: 「system_ssh_add-users-and-change-sshd-config-and-firewall」をbinディレクトリに配置する 
  template:
    src: system_ssh_reset-sshd-config-and-firewall_and_remove-users
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「system_vim_install」をbinディレクトリに配置する 
  template:
    src: system_vim_install
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「system_vnc_server_install」をbinディレクトリに配置する
  template:
    src: system_vnc_server_install
    dest: '{{ ansible_user_dir }}/ansible/bin/{{ item.key }}/'
    force: yes
  with_dict: "{{ ipv4 }}"
