- name: wp-content ディレクトリを削除する
  become: yes
  file:
    path: "{{ wp_installed_path }}/wp-content"
    state: absent

- name: wp-content ディレクトリのデータを更新する
  become: yes
  command: "mv {{ restore_work_dir }}/wp-content {{ wp_installed_path }}/wp-content"

- name: wp-content ディレクトリの権限を Apache へ付与する
  become: yes
  file:
    path: "{{ wp_installed_path }}/wp-content"
    owner: apache
    group: apache
    mode: 0755
    recurse: yes
