- name: EPELをインストールする
  become: yes
  include_role:
    name: system/packages/epel/install

- name: pipをインストールする
  become: yes
  include_role:
    name: system/pip/install

- name: Xvfbをインストールする
  become: yes
  yum:
    name: xorg-x11-server-Xvfb
    state: latest

- name: pyvirtualdisplayをインストールする
  become: yes
  pip:
    name: pyvirtualdisplay

- name: Python Seleniumをインストールする
  become: yes
  pip:
    name: selenium
