- name: EPELリポジトリをインストールする
  become: yes
  include_role:
    name: system/packages/epel/install

- name: Remiリポジトリをインストールする
  become: yes
  include_role:
    name: system/packages/remi/install

- name: PHP7.1をインストールする 
  become: yes
  yum:
    name: '{{ item }}'
    enablerepo: remi-php71
    state: latest
  loop:
    - php
    - php-gd
    - php-gmp
    - php-intl
    - php-ldap
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-opcache
    - php-pdo
    - php-pear 
    - php-pear-Net-Curl
    - php-pecl-apcu-bc
    - php-pecl-redis
    - php-pecl-zip
    - php-soap
    - php-xml

- name: タイムゾーンを「Asia/Tokyo」に設定する
  become: yes
  ini_file:
    dest: /etc/php.ini
    section: Date
    option: date.timezone
    value: "Asia/Tokyo"
