- name: EPELをインストール
  become: yes
  yum:
    name: 'epel-release'
    state: present

- name: 日本語関連のパッケージをインストール
  become: yes
  yum:
    name: ibus-kkc
    state: present

- name: 日本語関連のパッケージをインストール
  become: yes
  yum:
    name: vlgothic-*
    state: present

- name: システムの文字セットをUTF-8へ変更
  become: yes
  shell: localectl set-locale LANG=ja_JP.UTF-8

- name: システムの文字セットの変更を繁栄させる
  become: yes
  shell: source /etc/locale.conf

- name: pipをインストール
  become: yes
  yum:
    name: python-pip
    state: present

- name: pipをアップデート
  become: yes
  shell: pip install --upgrade pip

- name: pexpectをインストール #Ansibleでexpectを利用するためのライブラリ
  become: yes
  shell: pip install pexpect

- name: VNCサーバ構築に必要なツールのインストール
  become: yes
  yum:
    name: 'tigervnc-server'
    state: present

- name: GNOMEデスクトップをインストール
  become: yes
  shell: yum -y groupinstall GNOME Desktop

- name: VNCサーバの設定 / 設定ファイルのコピー
  become: yes
  shell: cp /lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@:1.service

- name: VNCサーバの設定 / 設定ファイルの書き換え
  become: yes
  replace: 
    dest: /etc/systemd/system/vncserver@:1.service
    regexp: '<USER>'
    replace: "{{ vnc_user }}"

- name: ファイアウォールの設定 / vnc-serverを追加
  become: yes
  shell: firewall-cmd --permanent --add-service vnc-server

- name: ファイウォールの設定 / ファイアウォールを再スタート
  become: yes
  shell: systemctl restart firewalld.service

- name: VNCユーザーの設定 / VNCユーザーを追加
  become: yes
  user: 
    name: "{{ vnc_user }}"
    password: "{{ vnc_password }} |password_hash('sha512')"

- name: /.vncを作成する
  file:
    path: "/home/{{ vnc_user }}/.vnc"
    state: directory
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0755

- name: passwordファイルを作成する
  shell: "echo {{ vnc_password }} | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd"

- name: /.vncの権限を変更する
  file:
    path: "/home/{{ vnc_user }}/.vnc/passwd"
    state: file
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0600


#- name: VNCユーザーの設定 / VNCパスワードを設定
#  become: yes  
#  become_user: "{{ vnc_user }}"
#  become_method: su
#  expect:
#    command: vncpasswd 
#    responses:
#      "Password:" : "{{ vnc_password }}"
#      "Verify:" : "{{ vnc_password }}"

- name: systemdに設定ファイルを再度読込みをさせる
  become: yes
  shell: systemctl daemon-reload

# - name: VNCサービスの停止 (http://srobb.net/rhvnc.html)
#   shell: pkill vnc

- name: VNCサービスの起動
  become: yes
  shell: systemctl start vncserver@:1.service

- name: VNCサービスの自動起動設定を行う
  become: yes
  shell: systemctl enable vncserver@:1.service
