# Zabbixデータベース情報
# 環境に応じて変更する事
#----------------------------------------------------
zabbix_agent_port: 10050
#----------------------------------------------------


# Zabbix RPM URL
zabbix_release_rpm_url: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm  
