- name: Rustをインストールする
  become: yes
  shell: curl -L http://static.rust-lang.org/rustup.sh | sh

- name: 必要なパッケージをインストールする
  become: yes
  yum:
    name: '{{ item }}'
    state: present 
  loop:
    - libgit2
    - cmake

- name: exaをインストールする
  become: yes
  shell: cargo install --no-default-features exa
 
- name: exaのバイナリファイルを「/usr/local/bin」へコピーする
  become: yes
  copy:
    src: /root/.cargo/bin/exa 
    dest: /usr/local/bin/exa
    mode: 0755 
    owner: root
    group: root
    remote_src: yes

- name: 「/root/.cargo/bin/exa」のバイナリファイルを削除する
  become: yes
  file:
    path: /root/.cargo/bin/exa 
    state: absent 
