- name: Passengerのインストールに必要なライブラリをインストールする
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  loop:
    - curl-devel
    - gcc
    - gcc-c++
    - httpd-devel
    - openssl-devel
    - zlib-devel

- name: Passengerがインストールされているか調べる
  command: test -f /usr/local/bin/passenger-install-apache2-module
  register: PASSENGER_INSTALLED
  ignore_errors: yes

- name: Passengerをインストールする
  become: yes
  gem:
    name: passenger
    user_install: no
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: PASSENGER_INSTALLED is failed 

- name: PassengerのApache用モジュールをインストールする
  become: yes
  command: passenger-install-apache2-module --auto
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: PASSENGER_INSTALLED is failed 

- name: PassengerのApache用モジュールの設定を取得する
  command: passenger-install-apache2-module --snippet
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: PASSENGER_SNIPPET_VARS
  when: PASSENGER_INSTALLED is failed 

- name: redmine.confを作成する
  become: yes
  template:
    src: redmine.conf
    dest: "/etc/httpd/conf.d/{{ httpd_conf_confd }}"
  when: PASSENGER_INSTALLED is failed 

- name: httpdを再起動する
  become: yes
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: PASSENGER_INSTALLED is failed 
