- name: 作業用ディレクトリを初期化する
  become: yes
  file:
    path: '{{ work_dir }}'
    state: absent

- name: 作業用ディレクトリを作成する 
  become: yes
  file:
    path: '{{ work_dir }}'
    state: directory
    mode: 0755

- name: Rubyインストールに必要なパッケージをインストールする
  become: yes
  yum:
    name: '{{ item }}'
    state: latest
  loop:
    - bzip2
    - curl-devel
    - gcc
    - gdbm-devel
    - git
    - libffi-devel
    - libyaml-devel
    - ncurses-devel
    - openssl-devel
    - readline-devel
    - zlib-devel

- name: Rubyがインストールされているか確認する
  command: ruby --version
  register: RUBY_INSTALLED
  ignore_errors: yes

- name: Rubyのソースコードをダウンロードする
  get_url:
    url: "{{ ruby_url_dir }}/{{ ruby_archive_name }}"
    dest: '{{ work_dir }}'
  when: RUBY_INSTALLED is failed 

- name: Rubyのソースコードを展開する
  unarchive:
    src: "{{ work_dir }}/{{ ruby_archive_name }}"
    dest: '{{ work_dir }}'
    copy: no
  when: RUBY_INSTALLED is failed 

- name: Makefileを作成する (configure)
  command: ./configure --disable-install-doc
  args:
    chdir: "{{ work_dir }}/{{ ruby_archive_version }}"
  when: RUBY_INSTALLED is failed 

- name: ソールファイルをコンパイルする (make)
  command: make
  args:
    chdir: "{{ work_dir }}/{{ ruby_archive_version }}"
  when: RUBY_INSTALLED is failed 

- name: Rubyをインストールする
  become: yes
  command: make install
  args:
    chdir: "{{ work_dir }}/{{ ruby_archive_version }}"
  when: RUBY_INSTALLED is failed 
