- name: Jenkinsをアンインストールする
  become: yes
  yum:
    name: jenkins
    state: absent

- name: 関連ディレクトリを削除する
  become: yes
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /var/cache/jenkins
    - /var/lib/jenkins
    - /var/log/jenkins

- name: httpdサービスを停止する
  become: yes
  service: 
    name: httpd
    state: stopped
    enabled: yes

- name: httpdサービスを起動する
  become: yes
  service: 
    name: httpd
    state: started
    enabled: yes
