- name: Apache（httpd）をインストールする
  become: yes
  yum: 
    name: httpd 
    state: latest

- name: firewalldでHTTPを許可する
  become: yes
  firewalld: 
    service: http
    state: enabled 
    permanent: true
    immediate: true

- name: httpdサービスを起動する
  become: yes
  service: 
    name: httpd
    state: started
    enabled: yes
