- name: MariaDBリポジトリを追加する
  become: yes
  yum_repository:
    name: mariadb
    file: MariaDB
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    state: present

- name: mariadb-devel、mariadb-serverをインストールする
  become: yes
  yum: 
    name: '{{ item }}'
  with_items:
    - MariaDB-devel
    - MariaDB-server
  
- name: MySQL-pythonをインストールする (Ansibleが使用)
  become: yes
  yum: 
    name: MySQL-python

- name: /etc/my.cnfを作成する
  become: yes
  template: 
    src: my.cnf 
    dest: /etc/my.cnf
    owner: root
    group: root 
    mode: 0644

- name: MariaDBを起動し自動起動設定をする
  become: yes
  service:
    name: mariadb
    state: started
    enabled: yes

- name: 匿名ユーザーを削除する
  become: yes
  mysql_user:
    name: ''
    state: absent
  register: result
  ignore_errors: true

#- name: リモートからのrootログインを禁止
#  mysql_user:
#    name: root
#    host: '{{ ansible_fqdn }}'
#    state: absent

- name: testデータベースを削除する
  become: yes
  mysql_db:
    name: test
    state: absent
  ignore_errors: true

- name: rootパスワードを設定する
  become: yes
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}" 
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: MariaDBを再起動する
  become: yes
  service:
    name: mariadb
    state: restarted
    enabled: yes
