---
- hosts: all
  vars_files:
    - vars/redmine/install/default.yml
  become: yes 

  roles:
    - httpd/install
    - language/ruby/install/source
    - rdb/pg/install
    - redmine/create_pg_account_and_database
    - redmine/install
    - httpd/passenger/install
