---
- hosts: all
  vars_files:
    - vars/rdb/mariadb/default.yml
    - vars/wordpress/default.yml
  become: yes 
  
  roles:
    - role: httpd/install
      tags: httpd_install
    - role: language/php70/install
      tags: language_php70_install
    - role: rdb/mariadb/install
      tags: rdb_mariadb_install
    - role: rdb/mariadb/create_database
      tags: rdb_mariadb_create-database
    - role: wordpress/install
      tags: wordpress_install
