- name: Javaをインストールする 
  become: yes
  yum: 
    name: java
    state: latest

- name: Jenkinsリポジトリをシステムに追加する
  become: yes
  yum_repository:
    name: jenkins
    description: Jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: yes
    gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

- name: Jenkinsをインストールする
  become: yes
  yum:
    name: jenkins
    state: latest

- name: Jenkinsを起動する
  become: yes
  service:
    name: jenkins
    state: running
    enabled: yes

- name: Jenkinsが利用するポート（8080） を解放する
  become: yes
  firewalld:
    port: 8080/tcp
    permanent: yes 
    state: enabled
    immediate: yes
