httpd_conf_confd: jenkis.conf

jenkins_dir: jenkins

#----------------------------------------------------                                        
# アクセスをコントロールするIPアドレス／ドメイン
#----------------------------------------------------                                        
requires:
  example.com: Require host example.com
  127.0.0.1: Require ip 127.0.0.1
