# ownCloudデータベース情報                                                                  
# 環境に応じて変更する事                                                                     
#----------------------------------------------------                                        
db_name: owncloud 
db_user: owncloud
db_password: owncloud 
db_host: localhost                                                                           
oc_install_dir: /var/www/html/owncloud
#----------------------------------------------------                                        

# Apacheの.htaccessを制御するファイル
oc_httpd_conf: owncloud.conf
#----------------------------------------------------
