- name: 「ansible/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/ansible/install'
    recurse: yes
    state: directory

- name: 「ansible/install」をbinディレクトリに配置する
  template:
    src: 'ansible/install'
    dest: '{{ ansible_user_dir }}/ansible/bin/ansible/install/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「jenkins/create-backup」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/jenkins/create-backup'
    recurse: yes
    state: directory

- name: 「jenkins/create-backup」をbinディレクトリに配置する
  template:
    src: 'jenkins/create-backup'
    dest: '{{ ansible_user_dir }}/ansible/bin/jenkins/create-backup/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「jenkins/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/jenkins/install'
    recurse: yes
    state: directory

- name: 「jenkins/install」をbinディレクトリに配置する
  template:
    src: 'jenkins/install'
    dest: '{{ ansible_user_dir }}/ansible/bin/jenkins/install/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「jenkins/restore」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/jenkins/restore'
    recurse: yes
    state: directory

- name: 「jenkins/restore」をbinディレクトリに配置する
  template:
    src: 'jenkins/restore'
    dest: '{{ ansible_user_dir }}/ansible/bin/jenkins/restore/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「owncloud/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/owncloud/install'
    recurse: yes
    state: directory

- name: 「owncloud/install」をbinディレクトリに配置する
  template:
    src: owncloud/install
    dest: '{{ ansible_user_dir }}/ansible/bin/owncloud/install/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「redmine/create-backup」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/redmine/create-backup'
    recurse: yes
    state: directory

- name: 「redmine/create-backup」をbinディレクトリに配置する
  template:
    src: redmine/create-backup
    dest: '{{ ansible_user_dir }}/ansible/bin/redmine/create-backup/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「redmine/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/redmine/install'
    recurse: yes
    state: directory

- name: 「redmine/install」をbinディレクトリに配置する
  template:
    src: redmine/install
    dest: '{{ ansible_user_dir }}/ansible/bin/redmine/install/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「redmine/restore」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/redmine/restore'
    recurse: yes
    state: directory

- name: 「redmine/restore」をbinディレクトリに配置する
  template:
    src: redmine/restore
    dest: '{{ ansible_user_dir }}/ansible/bin/redmine/restore/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「selenium/python/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/selenium/python/install'
    recurse: yes
    state: directory

- name: 「selenium/python/install」をbinディレクトリに配置する 
  template:
    src: selenium/python/install
    dest: '{{ ansible_user_dir }}/ansible/bin/selenium/python/install/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「system/ssh/add-users-and-change-sshd-config-and-firewall」を配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/system/ssh/add-users-and-change-sshd-config-and-firewall'
    recurse: yes
    state: directory

- name: 「system/ssh/add-users-and-change-sshd-config-and-firewall」をbinディレクトリに配置する 
  template:
    src: system/ssh/add-users-and-change-sshd-config-and-firewall 
    dest: 
      '{{ ansible_user_dir }}/ansible/bin/system/ssh/add-users-and-change-sshd-config-and-firewall/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「system/ssh/reset-sshd-config-and-firewall_and_remove-users」を配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/system/ssh/reset-sshd-config-and-firewall_and_remove-users'
    recurse: yes
    state: directory

- name: 「system/ssh/reset-sshd-config-and-firewall_and_remove-users」をbinディレクトリに配置する 
  template:
    src: system/ssh/reset-sshd-config-and-firewall_and_remove-users
    dest: '{{ ansible_user_dir }}/ansible/bin/system/ssh/reset-sshd-config-and-firewall_and_remove-users/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「system/update-and-set-selinux-disabled」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/system/update-and-set-selinux-disabled'
    recurse: yes
    state: directory

- name: 「system/update-and-set-selinux-disabled」をbinディレクトリに配置する 
  template:
    src: system/update-and-set-selinux-disabled 
    dest: '{{ ansible_user_dir }}/ansible/bin/system/update-and-set-selinux-disabled/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「vim/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/vim/install'
    recurse: yes
    state: directory

- name: 「vim/install」をbinディレクトリに配置する 
  template:
    src: vim/install
    dest: '{{ ansible_user_dir }}/ansible/bin/vim/install/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「vnc/server/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/vnc/server/install'
    recurse: yes
    state: directory

- name: 「vnc/server/install」をbinディレクトリに配置する
  template:
    src: vnc/server/install
    dest: '{{ ansible_user_dir }}/ansible/bin/vnc/server/install/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「wordpress/create-backup」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/wordpress/create-backup'
    recurse: yes
    state: directory

- name: 「wordpress/create-backup」をbinディレクトリに配置する
  template:
    src: wordpress/create-backup
    dest: '{{ ansible_user_dir }}/ansible/bin/wordpress/create-backup/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「wordpress/install」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/wordpress/install'
    recurse: yes
    state: directory

- name: 「wordpress/install」をbinディレクトリに配置する
  template:
    src: wordpress/install
    dest: '{{ ansible_user_dir }}/ansible/bin/wordpress/install/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「wordpress/uninstall」を配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/wordpress/uninstall'
    recurse: yes
    state: directory

- name: 「wordpress/uninstall」をbinディレクトリに配置する
  template:
    src: wordpress/uninstall
    dest: '{{ ansible_user_dir }}/ansible/bin/wordpress/uninstall/{{ item.value.name }}.sh'
    mode: 0755
    force: yes
  with_dict: "{{ ipv4 }}"

- name: テストスクリプトを配置するディレクトリを作成する
  file:
    path: '{{ ansible_user_dir }}/ansible/bin/tests'
    recurse: yes
    state: directory

- name: shunit2をGitリポジトリから取得する
  git:
    repo: https://github.com/kward/shunit2.git
    dest: '{{ ansible_user_dir }}/ansible/bin/shunit2'

- name: 「tests/jenkins/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」テストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/jenkins/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false/'
    recurse: yes
    state: directory

- name: 「tests/jenkins/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」を配置する
  template:
    src: tests/jenkins/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/jenkins/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/jenkins/restore/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」をテストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/jenkins/restore/no-extra-vars-argument-should-cause-stderr-and-return-false'
    recurse: yes
    state: directory

- name: 「tests/jenkins/restore/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」を配置する
  template:
    src: tests/jenkins/restore/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/jenkins/restore/no-extra-vars-argument-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/redmine/create-backup/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」テストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/create-backup/invalid-extra-vars-name-should-cause-stderr-and-return-false/'
    recurse: yes
    state: directory

- name: 「tests/redmine/create-backup/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」を配置する
  template:
    src: tests/redmine/create-backup/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/create-backup/invalid-extra-vars-name-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/redmine/create-backup/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」をテストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/create-backup/no-extra-vars-argument-should-cause-stderr-and-return-false'
    recurse: yes
    state: directory

- name: 「tests/redmine/create-backup/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」を配置する
  template:
    src: tests/redmine/create-backup/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/create-backup/no-extra-vars-argument-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"


- name: 「tests/redmine/install/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」テストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/install/invalid-extra-vars-name-should-cause-stderr-and-return-false/'
    recurse: yes
    state: directory

- name: 「tests/redmine/install/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」を配置する
  template:
    src: tests/redmine/install/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/install/invalid-extra-vars-name-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/redmine/install/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」をテストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/install/no-extra-vars-argument-should-cause-stderr-and-return-false'
    recurse: yes
    state: directory

- name: 「tests/redmine/install/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」を配置する
  template:
    src: tests/redmine/install/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/install/no-extra-vars-argument-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/redmine/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」テストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false/'
    recurse: yes
    state: directory

- name: 「tests/redmine/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」を配置する
  template:
    src: tests/redmine/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/restore/invalid-extra-vars-name-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/redmine/restore/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」をテストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/restore/no-extra-vars-argument-should-cause-stderr-and-return-false'
    recurse: yes
    state: directory

- name: 「tests/redmine/restore/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」を配置する
  template:
    src: tests/redmine/restore/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/redmine/restore/no-extra-vars-argument-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/wordpress/install/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」テストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/wordpress/install/invalid-extra-vars-name-should-cause-stderr-and-return-false/'
    recurse: yes
    state: directory

- name: 「tests/wordpress/install/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh」を配置する
  template:
    src: tests/wordpress/install/invalid-extra-vars-name-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/wordpress/install/invalid-extra-vars-name-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"

- name: 「tests/wordpress/install/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」をテストスクリプトを配置するディレクトリを作成する
  file:
    path:
      '{{ ansible_user_dir }}/ansible/bin/tests/wordpress/install/no-extra-vars-argument-should-cause-stderr-and-return-false'
    recurse: yes
    state: directory

- name: 「tests/wordpress/install/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 」を配置する
  template:
    src: tests/wordpress/install/no-extra-vars-argument-should-cause-stderr-and-return-false.sh 
    dest:
      '{{ ansible_user_dir }}/ansible/bin/tests/wordpress/install/no-extra-vars-argument-should-cause-stderr-and-return-false/{{ item.value.name }}.sh'
    force: yes
  with_dict: "{{ ipv4 }}"
