- name: 必要なパッケージをインストールする
  sudo: yes
  yum:
    name: 'epel-release'
    state: latest

- name: pipをインストールする
  sudo: yes
  yum:
    name: 'python-pip'
    state: latest

- name: pipをアップグレードする
  sudo: yes
  shell: pip install --upgrade pip

- name: Xvfbをインストールする
  sudo: yes
  yum:
    name: xorg-x11-server-Xvfb
    state: latest

- name: pyvirtualdisplayをインストールする
  sudo: yes
  shell: pip install pyvirtualdisplay

- name: Firefoxをインストールする
  sudo: yes
  yum:
    name: firefox
    state: latest

- name: Geckodriverをダウンロードし解凍するパスへ配置する
  unarchive:
    src: '{{ geckodriver_url }}'
    dest: /usr/local/bin
    remote_src: True

- name: Python Seleniumをインストールする
  shell: pip install selenium

- name: Seleniumテストスクリプトをデプロイサーバへアップロードする
  template:
    src: install_test.py
    dest: /tmp

- name: Seleniumのインストールテストを実行する
  shell: python /tmp/install_test.py
  register: RESULT

- name: Seleniumがインストールされたか確認する
  debug: var=RESULT

