# Redmine create backup data vars

#----------------------------------------
# 適宜変更する
#----------------------------------------
# RDBMSのデータベースユーザー名
db_user: redmine
# RDBMSのデータベースパスワード
db_password: redmine
# RDBMSのデータベース名
db_name: redmine

# 将来的に実装予定
# RDBMSの稼働するマシンのホスト名
# db_host: localhost
#
# RDBMSの稼働するするマシンの接続ポート番号
# db_port: 5432
#----------------------------------------

# Backup data path
backup_data_path: /tmp

# Backup data group
backup_data_group: root

# Backup data owner
backup_data_ownder: root

# Redmine Directory
redmine_dir: /var/lib/redmine

# Git Directory
git_dir: /var/git

# Git archive data file
git_archive_file: git.tar.gz

# WordPress solution-log backup git Directory
wp_backup_solution_log_git_dir: /home/wpbackup/git/solution-log

# WordPress solution-log backup git archive data file
wp_backup_solution_log_git_archive_file: solution-log-backup.tar.gz

# Jenkins backup git Directory
jenkins_backup_git_dir: /home/jenkinsbackup/git/backup

# Jenkins backup git archive data file
jenkins_backup_git_archive_file: jenkins-backup.tar.gz

# Redmine media archie data file
redmine_media_archive_file: files.tar.gz

# PostgreSQL dump data file
pg_dump_data_file: redmine.psql
